apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
  labels:
    app: webapp
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webapp
    release: {{ .Release.Name }}
